name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
      - uses: lowlighter/metrics@latest
        with:
          # ... other options
          plugin_music: yes
          plugin_music_limit: 4                   # Limit to 4 entries
          plugin_music_playlist: https://open.spotify.com/embed/playlist/37i9dQZF1EpydEP0aT1C8i?utm_source=generator # Use extracted playlist link
          # plugin_music_provider: (will be guessed through plugin_music_playlist)
          # plugin_music_mode: (will be set to "playlist" when plugin_music_playlist is provided)
